<a href="https://colab.research.google.com/github/HrushhikeshMate/python-practice/blob/main/3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [1]:
count =0
while count <5:
  print(count)
  count+= 1

0
1
2
3
4


In [5]:
n =10
sum=0
count=1

while count <=n:
  sum =sum+ count
  count +=1

print(sum)

55


In [10]:
count=0
for i in range(11):
  count+=i

print(count)


55


In [19]:
count=0
for i in range(1,101):
  if i >1:
    for x in range(2,i):
      if i%x==0:
        break
    else:
      print(i, end= ' ')
      count+=1

print('\n the count is :',count)

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 
 the count is : 25


In [ ]:
for
