<a href="https://colab.research.google.com/github/HrushhikeshMate/python-practice/blob/main/3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [1]:
count =0
while count <5:
  print(count)
  count+= 1

0
1
2
3
4


In [5]:
n =10
sum=0
count=1

while count <=n:
  sum =sum+ count
  count +=1

print(sum)

55


In [10]:
count=0
for i in range(11):
  count+=i

print(count)


55


In [19]:
count=0
for i in range(1,101):
  if i >1:
    for x in range(2,i):
      if i%x==0:
        break
    else:
      print(i, end= ' ')
      count+=1

print('\n the count is :',count)

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 
 the count is : 25


In [22]:
lit=[]
for i in range(10):
  lit.append(i**2)
print(lit)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [23]:
[i**2 for i in range(15) ]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [24]:
add = lambda a,d:a*d

add(5,6)


30

# pandas


In [2]:
import pandas as pd


In [3]:
data= {'Name':['me','kate','anay'],
       'Age':[24,35,24],
       'city': ['nashik','nagpur','dublin']

}

In [4]:
df=pd.DataFrame(data)

In [5]:
# If you want to see the index, you can simply use df.index
print(df.index)

# If you want to filter the DataFrame based on the index, you would use square brackets
# For example, to get the row with index 0:
print(df.loc[0])

RangeIndex(start=0, stop=3, step=1)
Name        me
Age         24
city    nashik
Name: 0, dtype: object


In [6]:
print(df.to_string(index=False))

Name  Age   city
  me   24 nashik
kate   35 nagpur
anay   24 dublin


In [7]:
url='https://raw.githubusercontent.com/krishnaik06/Complete-Python-Bootcamp/refs/heads/main/10-Data%20Analysis%20With%20Python/data.csv'
df= pd.read_csv(url)
df.head()

Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [8]:
df.describe()

Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [9]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [10]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [11]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [17]:
# shows how many missing value are there from the columns from dataset
df.isnull().sum()

Date            0
Category        0
Value           3
Product         0
Sales           4
Region          0
sales_fillna    0
dtype: int64

In [16]:
df['sales_fillna'] = df['Sales'].fillna(df['Sales'].mean())

In [19]:
#rename columns
df= df.rename(columns={'Date':'Sales_Date'})

In [22]:
df.head()

Sales_Date Category  Value   Product  Sales Region  sales_fillna  value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0       28.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0       39.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0       32.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0        8.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0       26.0

In [21]:
df['value_new']= df['Value'].fillna(df['Value'].mean().astype(int))

In [ ]:
df