<a href="https://colab.research.google.com/github/HrushhikeshMate/python-practice/blob/main/3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [1]:
count =0
while count <5:
  print(count)
  count+= 1

0
1
2
3
4


In [5]:
n =10
sum=0
count=1

while count <=n:
  sum =sum+ count
  count +=1

print(sum)

55


In [10]:
count=0
for i in range(11):
  count+=i

print(count)


55


In [19]:
count=0
for i in range(1,101):
  if i >1:
    for x in range(2,i):
      if i%x==0:
        break
    else:
      print(i, end= ' ')
      count+=1

print('\n the count is :',count)

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 
 the count is : 25


In [22]:
lit=[]
for i in range(10):
  lit.append(i**2)
print(lit)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [23]:
[i**2 for i in range(15) ]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [24]:
add = lambda a,d:a*d

add(5,6)


30

# pandas


In [25]:
import pandas as pd


In [27]:
data= {'Name':['me','kate','anay'],
       'Age':[24,35,24],
       'city': ['nashik','nagpur','dublin']

}

In [29]:
df=pd.DataFrame(data)

In [36]:
# If you want to see the index, you can simply use df.index
print(df.index)

# If you want to filter the DataFrame based on the index, you would use square brackets
# For example, to get the row with index 0:
print(df.loc[0])

RangeIndex(start=0, stop=3, step=1)
Name        me
Age         24
city    nashik
Name: 0, dtype: object


In [39]:
print(df.to_string(index=False))

Name  Age   city
  me   24 nashik
kate   35 nagpur
anay   24 dublin
