<a href="https://colab.research.google.com/github/HrushhikeshMate/python-practice/blob/main/3_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])